services:
  - type: web
    name: kenjitsu
    env: node
    plan: free 
    branch: main  
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    autoDeploy: false
  
